plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':domain')
    implementation 'org.springframework.boot:spring-boot-starter'

    runtimeOnly project(':web')
    runtimeOnly project(':persistence')

    testImplementation project(':domain')
    testImplementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}
